// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * G​i​t​H​u​b
		 */
		github: string
	}
	hero: {
		/**
		 * C​o​m​m​u​n​i​t​y​ ​R​e​s​o​u​r​c​e​s
		 */
		label: string
		/**
		 * {​c​o​u​n​t​}​ ​P​r​o​j​e​c​t​s
		 * @param {unknown} count
		 */
		projectCount: RequiredParams<'count'>
		/**
		 * A​w​e​s​o​m​e
		 */
		titleLine1: string
		/**
		 * A​r​k​n​i​g​h​t​s​ ​E​n​d​f​i​e​l​d
		 */
		titleLine2: string
		/**
		 * A​ ​c​u​r​a​t​e​d​ ​c​o​l​l​e​c​t​i​o​n​ ​o​f​ ​t​o​o​l​s​,​ ​r​e​s​o​u​r​c​e​s​,​ ​a​n​d​ ​c​o​m​m​u​n​i​t​y​ ​p​r​o​j​e​c​t​s​ ​f​o​r​ ​A​r​k​n​i​g​h​t​s​:​ ​E​n​d​f​i​e​l​d​ ​—​ ​m​a​i​n​t​a​i​n​e​d​ ​b​y​ ​t​h​e​ ​c​o​m​m​u​n​i​t​y​.
		 */
		description: string
		/**
		 * E​x​p​l​o​r​e
		 */
		explore: string
		/**
		 * G​i​t​H​u​b
		 */
		github: string
	}
	search: {
		/**
		 * S​e​a​r​c​h​ ​p​r​o​j​e​c​t​s​.​.​.
		 */
		placeholder: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		category: string
	}
	sidebar: {
		/**
		 * C​l​e​a​r
		 */
		clear: string
	}
	projectCard: {
	}
	drawer: {
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * N​o​.
		 */
		index: string
		/**
		 * A​u​t​h​o​r
		 */
		author: string
		/**
		 * A​d​d​e​d
		 */
		added: string
		/**
		 * L​i​c​e​n​s​e
		 */
		license: string
		/**
		 * S​o​u​r​c​e
		 */
		source: string
		/**
		 * R​e​p​o​s​i​t​o​r​y
		 */
		repository: string
		/**
		 * W​e​b​s​i​t​e​s
		 */
		websites: string
		/**
		 * O​p​e​n​ ​S​o​u​r​c​e
		 */
		openSource: string
		/**
		 * C​l​o​s​e​d​ ​S​o​u​r​c​e
		 */
		closedSource: string
		/**
		 * N​o​ ​s​c​r​e​e​n​s​h​o​t​s
		 */
		noScreenshots: string
	}
	gallery: {
		/**
		 * N​o​ ​p​r​o​j​e​c​t​s​ ​f​o​u​n​d​.
		 */
		noResults: string
		/**
		 * T​r​y​ ​a​d​j​u​s​t​i​n​g​ ​y​o​u​r​ ​s​e​a​r​c​h​ ​o​r​ ​f​i​l​t​e​r​s​.
		 */
		noResultsHint: string
	}
	footer: {
		/**
		 * C​o​n​t​r​i​b​u​t​e
		 */
		contribute: string
		/**
		 * A​w​e​s​o​m​e​ ​A​r​k​n​i​g​h​t​s
		 */
		awesomeArknights: string
	}
	language: {
		/**
		 * L​a​n​g​u​a​g​e
		 */
		label: string
	}
	theme: {
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​d​a​r​k​ ​m​o​d​e
		 */
		switchToDark: string
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​l​i​g​h​t​ ​m​o​d​e
		 */
		switchToLight: string
		/**
		 * D​a​r​k
		 */
		dark: string
		/**
		 * L​i​g​h​t
		 */
		light: string
	}
}

export type TranslationFunctions = {
	nav: {
		/**
		 * GitHub
		 */
		github: () => LocalizedString
	}
	hero: {
		/**
		 * Community Resources
		 */
		label: () => LocalizedString
		/**
		 * {count} Projects
		 */
		projectCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * Awesome
		 */
		titleLine1: () => LocalizedString
		/**
		 * Arknights Endfield
		 */
		titleLine2: () => LocalizedString
		/**
		 * A curated collection of tools, resources, and community projects for Arknights: Endfield — maintained by the community.
		 */
		description: () => LocalizedString
		/**
		 * Explore
		 */
		explore: () => LocalizedString
		/**
		 * GitHub
		 */
		github: () => LocalizedString
	}
	search: {
		/**
		 * Search projects...
		 */
		placeholder: () => LocalizedString
		/**
		 * Category
		 */
		category: () => LocalizedString
	}
	sidebar: {
		/**
		 * Clear
		 */
		clear: () => LocalizedString
	}
	projectCard: {
	}
	drawer: {
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * No.
		 */
		index: () => LocalizedString
		/**
		 * Author
		 */
		author: () => LocalizedString
		/**
		 * Added
		 */
		added: () => LocalizedString
		/**
		 * License
		 */
		license: () => LocalizedString
		/**
		 * Source
		 */
		source: () => LocalizedString
		/**
		 * Repository
		 */
		repository: () => LocalizedString
		/**
		 * Websites
		 */
		websites: () => LocalizedString
		/**
		 * Open Source
		 */
		openSource: () => LocalizedString
		/**
		 * Closed Source
		 */
		closedSource: () => LocalizedString
		/**
		 * No screenshots
		 */
		noScreenshots: () => LocalizedString
	}
	gallery: {
		/**
		 * No projects found.
		 */
		noResults: () => LocalizedString
		/**
		 * Try adjusting your search or filters.
		 */
		noResultsHint: () => LocalizedString
	}
	footer: {
		/**
		 * Contribute
		 */
		contribute: () => LocalizedString
		/**
		 * Awesome Arknights
		 */
		awesomeArknights: () => LocalizedString
	}
	language: {
		/**
		 * Language
		 */
		label: () => LocalizedString
	}
	theme: {
		/**
		 * Switch to dark mode
		 */
		switchToDark: () => LocalizedString
		/**
		 * Switch to light mode
		 */
		switchToLight: () => LocalizedString
		/**
		 * Dark
		 */
		dark: () => LocalizedString
		/**
		 * Light
		 */
		light: () => LocalizedString
	}
}

export type Formatters = {}
