import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import chalk from 'chalk';
import { filterValidProjects, sortProjectsById } from '@/helpers';
import { CATEGORY_LABEL, LANGUAGES, WEBSITE_PROVIDER_LABEL } from '@/shared';
import type { Category, Language, Project } from '@/shared';
import data from '../../data/LIST.json';

/////////////////////////////////// Builder ///////////////////////////////////

const LINE_BREAK = '\n';

function generateLink(href: string, text: string) {
  return `[${text}](${href})`;
}

function generateBanner() {
  const BANNER = `<!--
  DO NOT EDIT THIS FILE DIRECTLY
  Generated by scripts/generate.ts
-->
`;
  return BANNER;
}

function generateHeading(title: string, level: number = 2) {
  const hashtag = Math.min(Math.max(level, 1), 6);
  return String.prototype.concat(`${'#'.repeat(hashtag)} ${title}`, LINE_BREAK);
}

function generateProject(project: Project, lang: Language) {
  const blocks: Array<string> = [];

  const name = project.repository
    ? generateLink(project.repository, project.name)
    : project.name;

  if (project.website) {
    for (const { url, provider } of project.website) {
      blocks.push(generateLink(url, WEBSITE_PROVIDER_LABEL[provider][lang]));
    }
  }

  const description = project.description[lang];
  blocks.push(description);

  return [`- ${name}`, ...blocks.map((b) => `  - ${b}`), LINE_BREAK].join(LINE_BREAK);
}

/////////////////////////////////// Update ///////////////////////////////////

const PROJECT_ROOT = resolve(process.cwd(), '../');

function generateFileName(lang: Language, prefix: string) {
  return lang === 'en-US' ? `${prefix}.md` : `${prefix}.${lang}.md`;
}

const LIST_MAP = LANGUAGES.reduce(
  (acc, lang) => ({
    ...acc,
    [lang]: generateFileName(lang, 'LIST'),
  }),
  {} as Record<Language, string>
);

const README_MAP = LANGUAGES.reduce(
  (acc, lang) => ({
    ...acc,
    [lang]: generateFileName(lang, 'README'),
  }),
  {} as Record<Language, string>
);

function generateBadge(count: number, text: string) {
  return `<img src="https://img.shields.io/badge/${text}-${count}-blue" alt="${text}" />`;
}

function updateReadmeBadge(lang: Language, count: number) {
  const BADGE_REGEX = /<!-- BADGE_COUNT_START -->[\s\S]*?<!-- BADGE_COUNT_END -->/;

  const fileName = README_MAP[lang];
  const readmeFile = resolve(PROJECT_ROOT, fileName);
  let content = readFileSync(readmeFile, 'utf-8');

  // Replace content between BADGE_COUNT_START and BADGE_COUNT_END
  if (BADGE_REGEX.test(content)) {
    const badgeLine = generateBadge(count, 'Projects');
    content = content.replace(
      BADGE_REGEX,
      `<!-- BADGE_COUNT_START -->\n  ${badgeLine}\n  <!-- BADGE_COUNT_END -->`
    );

    writeFileSync(readmeFile, content, 'utf-8');
    console.log(chalk.green(`Successfully updated badge count in ${fileName}`));
  } else {
    console.log(chalk.yellow(`Badge markers not found in ${fileName}`));
  }
}

function updateReadmeRecentProjects(lang: Language, projects: Array<Project>) {
  const RECENT_REGEX = /<!-- RECENT_START -->[\s\S]*?<!-- RECENT_END -->/;

  const fileName = README_MAP[lang];
  const readmeFile = resolve(PROJECT_ROOT, fileName);
  let content = readFileSync(readmeFile, 'utf-8');

  // Generate recent projects section
  const recentSection = projects
    .map((project) => generateProject(project, lang))
    .join('');

  // Replace content between RECENT_START and RECENT_END
  if (RECENT_REGEX.test(content)) {
    content = content.replace(
      RECENT_REGEX,
      `<!-- RECENT_START -->\n${recentSection.trim()}\n<!-- RECENT_END -->`
    );

    writeFileSync(readmeFile, content, 'utf-8');
    console.log(chalk.green(`Successfully updated recent projects in ${fileName}`));
  } else {
    console.log(chalk.yellow(`Recent markers not found in ${fileName}`));
  }
}

function generateList(lang: Language, projects: Array<Project>) {
  let doc = generateBanner();
  doc += LINE_BREAK;

  const groups = projects.reduce(
    (acc, project) => {
      const category = project.category;
      if (!acc[category]) {
        acc[category] = [];
      }
      acc[category].push(project);
      return acc;
    },
    {} as Record<Category, Array<Project>>
  );

  for (const [category, projects] of Object.entries(groups)) {
    doc += generateHeading(CATEGORY_LABEL[category as Category][lang]);
    doc += LINE_BREAK;

    projects.forEach((project) => {
      doc += generateProject(project, lang);
    });
  }

  // Remove trailing newline
  doc = doc.trimEnd() + LINE_BREAK;

  const fileName = LIST_MAP[lang];
  const outputFile = resolve(PROJECT_ROOT, fileName);

  writeFileSync(outputFile, doc, 'utf-8');

  console.log(chalk.green(`Successfully generated ${fileName}`));
}

const RECENT_COUNT = 5;

function main() {
  const validProjects = filterValidProjects(data as Array<Project>);
  const sortedProjects = sortProjectsById(validProjects);

  for (const lang of LANGUAGES) {
    generateList(lang, sortedProjects);
    updateReadmeBadge(lang, validProjects.length);
    updateReadmeRecentProjects(lang, sortedProjects.slice(-RECENT_COUNT));
  }
}

main();
